[project]
name = "speech"
version = "0.1.2"
description = "An experimental CLI for live-text-to-speech. Meant for live-coding performances."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyttsx3>=2.99",
]
